# Generated by Django 5.2 on 2025-05-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_user_name_alter_user_password'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['name', 'password'], name='crud_user_name_f3186a_idx'),
        ),
    ]
